/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type BallType = "leather" | "tape" | "tennis";

export type BattingStyle = "left_hand" | "right_hand";

export type BowlingStyle = "left_arm_chinaman" | "left_arm_fast" | "left_arm_medium" | "left_arm_orthodox" | "none" | "right_arm_fast" | "right_arm_legbreak" | "right_arm_medium" | "right_arm_offbreak";

export type DataRequestKind = "access" | "correction" | "erasure" | "objection";

export type DataRequestStatus = "in_progress" | "open" | "rejected" | "resolved";

export type DismissalKind = "bowled" | "caught" | "hit_ball_twice" | "hit_wicket" | "lbw" | "obstructing_the_field" | "retired_hurt" | "retired_out" | "run_out" | "stumped" | "timed_out";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type MatchResult = "abandoned" | "no_result" | "team_a_won" | "team_b_won" | "tie";

export type MatchStatus = "abandoned" | "cancelled" | "completed" | "forfeited" | "innings_break" | "live" | "scheduled" | "toss_done";

export type Numeric = ColumnType<string, number | string, number | string>;

export type StageKind = "final" | "group" | "knockout" | "super_league";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TossDecision = "bat" | "bowl";

export type TournamentRole = "organizer" | "scorer" | "team_manager";

export interface AuditLog {
  action: string;
  actor_user_id: string | null;
  after_state: Json | null;
  before_state: Json | null;
  created_at: Generated<Timestamp>;
  entity_id: string;
  entity_type: string;
  id: Generated<Int8>;
  reason: string | null;
}

export interface BattingCards {
  balls_faced: Generated<number>;
  fours: Generated<number>;
  innings_id: string;
  is_out: Generated<boolean>;
  player_id: string;
  position: number | null;
  runs: Generated<number>;
  sixes: Generated<number>;
}

export interface BowlingCards {
  innings_id: string;
  legal_balls: Generated<number>;
  maidens: Generated<number>;
  noballs: Generated<number>;
  player_id: string;
  runs_conceded: Generated<number>;
  wickets: Generated<number>;
  wides: Generated<number>;
}

export interface Clubs {
  city: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  logo_url: string | null;
  name: string;
}

export interface DataRequests {
  created_at: Generated<Timestamp>;
  details: string | null;
  handled_by: string | null;
  id: Generated<string>;
  kind: DataRequestKind;
  player_id: string | null;
  raised_by_email: string;
  resolution_note: string | null;
  resolved_at: Timestamp | null;
  status: Generated<DataRequestStatus>;
}

export interface Deliveries {
  ball_in_over: number;
  bowler_id: string;
  client_event_id: string;
  commentary: string | null;
  created_at: Generated<Timestamp>;
  extra_byes: Generated<number>;
  extra_legbyes: Generated<number>;
  extra_noballs: Generated<number>;
  extra_penalty: Generated<number>;
  extra_wides: Generated<number>;
  fielder_id: string | null;
  id: Generated<Int8>;
  innings_id: string;
  is_free_hit: Generated<boolean>;
  is_legal_delivery: Generated<boolean>;
  non_striker_id: string;
  over_number: number;
  player_out_id: string | null;
  runs_off_bat: Generated<number>;
  scored_by: string | null;
  sequence: number;
  striker_id: string;
  void_reason: string | null;
  voided_at: Timestamp | null;
  voided_by: string | null;
  wagon_angle_deg: number | null;
  wagon_distance: number | null;
  wicket_kind: DismissalKind | null;
}

export interface Grounds {
  city: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  latitude: Numeric | null;
  longitude: Numeric | null;
  name: string;
}

export interface Groups {
  id: Generated<string>;
  name: string;
  stage_id: string;
}

export interface GroupTeams {
  group_id: string;
  team_id: string;
}

export interface Innings {
  batting_team_id: string;
  bowling_team_id: string;
  closed_at: Timestamp | null;
  id: Generated<string>;
  innings_number: number;
  is_super_over: Generated<boolean>;
  match_id: string;
  max_overs: Numeric | null;
  target: number | null;
}

export interface InningsTotals {
  extras: Generated<number>;
  innings_id: string;
  legal_balls: Generated<number>;
  runs: Generated<number>;
  updated_at: Generated<Timestamp>;
  wickets: Generated<number>;
}

export interface Matches {
  actual_start: Timestamp | null;
  created_at: Generated<Timestamp>;
  ground_id: string | null;
  group_id: string | null;
  id: Generated<string>;
  match_number: number | null;
  overs_override: number | null;
  player_of_match_id: string | null;
  result: MatchResult | null;
  result_note: string | null;
  scheduled_start: Timestamp | null;
  stage_id: string | null;
  status: Generated<MatchStatus>;
  team_a_id: string;
  team_b_id: string;
  toss_decision: TossDecision | null;
  toss_winner_id: string | null;
  tournament_id: string;
  updated_at: Generated<Timestamp>;
  win_margin_runs: number | null;
  win_margin_wickets: number | null;
  winner_team_id: string | null;
}

export interface MatchInterruptions {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  innings_id: string;
  overs_remaining_after: Numeric;
  overs_remaining_before: Numeric;
  reason: string | null;
  recorded_by: string | null;
  wickets_lost_at: number;
}

export interface MatchPlayers {
  batting_order: number | null;
  is_captain: Generated<boolean>;
  is_keeper: Generated<boolean>;
  is_substitute: Generated<boolean>;
  match_id: string;
  player_id: string;
  team_id: string;
}

export interface MatchScorers {
  assigned_at: Generated<Timestamp>;
  is_primary: Generated<boolean>;
  match_id: string;
  user_id: string;
}

export interface NeonAuthAccount {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface NeonAuthInvitation {
  createdAt: Generated<Timestamp>;
  email: string;
  expiresAt: Timestamp;
  id: Generated<string>;
  inviterId: string;
  organizationId: string;
  role: string | null;
  status: string;
}

export interface NeonAuthJwks {
  createdAt: Timestamp;
  expiresAt: Timestamp | null;
  id: Generated<string>;
  privateKey: string;
  publicKey: string;
}

export interface NeonAuthMember {
  createdAt: Timestamp;
  id: Generated<string>;
  organizationId: string;
  role: string;
  userId: string;
}

export interface NeonAuthOrganization {
  createdAt: Timestamp;
  id: Generated<string>;
  logo: string | null;
  metadata: string | null;
  name: string;
  slug: string;
}

export interface NeonAuthProjectConfig {
  allow_localhost: boolean;
  created_at: Generated<Timestamp>;
  email_and_password: Json | null;
  email_provider: Json | null;
  endpoint_id: string;
  id: Generated<string>;
  name: string;
  plugin_configs: Json | null;
  social_providers: Json;
  trusted_origins: Json;
  updated_at: Generated<Timestamp>;
  webhook_config: Json | null;
}

export interface NeonAuthSession {
  activeOrganizationId: string | null;
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  impersonatedBy: string | null;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface NeonAuthUser {
  banExpires: Timestamp | null;
  banned: boolean | null;
  banReason: string | null;
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: Generated<string>;
  image: string | null;
  name: string;
  role: string | null;
  updatedAt: Generated<Timestamp>;
}

export interface NeonAuthVerification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface Partnerships {
  balls: Generated<number>;
  id: Generated<string>;
  innings_id: string;
  player_a_id: string;
  player_b_id: string;
  runs: Generated<number>;
  wicket_number: number;
}

export interface PlayerCareerStats {
  balls_faced: Generated<number>;
  best_bowling_runs: number | null;
  best_bowling_wkts: Generated<number>;
  catches: Generated<number>;
  fifties: Generated<number>;
  fours: Generated<number>;
  highest_score: Generated<number>;
  hundreds: Generated<number>;
  innings_batted: Generated<number>;
  innings_bowled: Generated<number>;
  legal_balls_bowled: Generated<number>;
  matches: Generated<number>;
  not_outs: Generated<number>;
  player_id: string;
  run_outs: Generated<number>;
  runs: Generated<number>;
  runs_conceded: Generated<number>;
  sixes: Generated<number>;
  stumpings: Generated<number>;
  updated_at: Generated<Timestamp>;
  wickets: Generated<number>;
}

export interface Players {
  batting: BattingStyle | null;
  bowling: BowlingStyle | null;
  claimed_at: Timestamp | null;
  claimed_by_user_id: string | null;
  consent_recorded_at: Timestamp | null;
  consent_recorded_by: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  date_of_birth: Timestamp | null;
  deleted_at: Timestamp | null;
  display_name: string | null;
  full_name: string;
  id: Generated<string>;
  is_minor: Generated<boolean>;
  merged_into_id: string | null;
  photo_url: string | null;
  suomisport_id: string | null;
}

export interface Stages {
  id: Generated<string>;
  kind: StageKind;
  name: string;
  sequence: number;
  tournament_id: string;
}

export interface Standings {
  balls_bowled: Generated<number>;
  balls_faced: Generated<number>;
  group_id: string;
  lost: Generated<number>;
  net_run_rate: Generated<Numeric>;
  no_result: Generated<number>;
  played: Generated<number>;
  points: Generated<number>;
  rank: number | null;
  runs_against: Generated<number>;
  runs_for: Generated<number>;
  team_id: string;
  tied: Generated<number>;
  updated_at: Generated<Timestamp>;
  won: Generated<number>;
}

export interface Teams {
  club_id: string | null;
  created_at: Generated<Timestamp>;
  home_city: string | null;
  id: Generated<string>;
  logo_url: string | null;
  name: string;
  short_name: string | null;
}

export interface TeamSquads {
  approved_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_captain: Generated<boolean>;
  is_keeper: Generated<boolean>;
  jersey_number: number | null;
  licence_verified: Generated<boolean>;
  licence_verified_at: Timestamp | null;
  licence_verified_by: string | null;
  player_id: string;
  team_id: string;
  tournament_id: string;
}

export interface TournamentMemberships {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  role: TournamentRole;
  team_id: string | null;
  tournament_id: string;
  user_id: string;
}

export interface TournamentRules {
  balls_per_over: Generated<number>;
  bonus_point_enabled: Generated<boolean>;
  dls_enabled: Generated<boolean>;
  free_hit_after_noball: Generated<boolean>;
  max_overs_per_bowler: number;
  noball_runs: Generated<number>;
  overs_per_innings: number;
  players_per_side: Generated<number>;
  points_loss: Generated<number>;
  points_no_result: Generated<number>;
  points_tie: Generated<number>;
  points_win: Generated<number>;
  powerplay_overs: Generated<number>;
  super_over_on_tie: Generated<boolean>;
  tournament_id: string;
  wide_runs: Generated<number>;
}

export interface Tournaments {
  ball: Generated<BallType>;
  country_code: Generated<string>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  ends_on: Timestamp | null;
  id: Generated<string>;
  is_public: Generated<boolean>;
  logo_url: string | null;
  name: string;
  organizer_org: string | null;
  season_year: number;
  slug: string;
  starts_on: Timestamp | null;
}

export interface TournamentTeams {
  registered_at: Generated<Timestamp>;
  team_id: string;
  tournament_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  display_name: string;
  email: string | null;
  google_sub: string | null;
  id: Generated<string>;
  is_platform_admin: Generated<boolean>;
  password_hash: string | null;
  phone: string | null;
}

export interface DB {
  audit_log: AuditLog;
  batting_cards: BattingCards;
  bowling_cards: BowlingCards;
  clubs: Clubs;
  data_requests: DataRequests;
  deliveries: Deliveries;
  grounds: Grounds;
  group_teams: GroupTeams;
  groups: Groups;
  innings: Innings;
  innings_totals: InningsTotals;
  match_interruptions: MatchInterruptions;
  match_players: MatchPlayers;
  match_scorers: MatchScorers;
  matches: Matches;
  "neon_auth.account": NeonAuthAccount;
  "neon_auth.invitation": NeonAuthInvitation;
  "neon_auth.jwks": NeonAuthJwks;
  "neon_auth.member": NeonAuthMember;
  "neon_auth.organization": NeonAuthOrganization;
  "neon_auth.project_config": NeonAuthProjectConfig;
  "neon_auth.session": NeonAuthSession;
  "neon_auth.user": NeonAuthUser;
  "neon_auth.verification": NeonAuthVerification;
  partnerships: Partnerships;
  player_career_stats: PlayerCareerStats;
  players: Players;
  stages: Stages;
  standings: Standings;
  team_squads: TeamSquads;
  teams: Teams;
  tournament_memberships: TournamentMemberships;
  tournament_rules: TournamentRules;
  tournament_teams: TournamentTeams;
  tournaments: Tournaments;
  users: Users;
}
